# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8a8e477bbc7dea6327f815880326bd4d266c1a635a9ae941c176cdbc5b617b049921561873a391a7aa4ecca8f90f75d3765ba71f98993101c449d3c824d0502

test:
  secret_key_base: 70b12819c5121e1b08c9be172dd2fd626d6f4be13139a30e9c4ad9f321089439f259757d2cdc6b80aaab31bb531008018c712ae18d5b55663da5e6f316006f9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
